const styles = {
  container: {
    background: "linear-gradient(180deg, #050814, #0b1020 35%, #111827)",
    color: "#eef2ff",
    minHeight: "100vh",
    fontFamily: "Arial, Helvetica, sans-serif",
  },
  wrap: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "24px",
  },
  hero: {
    marginBottom: "24px",
  },
  h1: {
    fontSize: "32px",
    fontWeight: "bold",
    margin: "0 0 10px",
  },
  h2: {
    fontSize: "20px",
    fontWeight: "bold",
    margin: "0 0 10px",
  },
  heroText: {
    color: "#9fb0d0",
    lineHeight: 1.45,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(12, 1fr)",
    gap: "16px",
  },
  card: {
    background: "rgba(18,26,43,.95)",
    border: "1px solid #2b3957",
    borderRadius: "20px",
    padding: "18px",
    boxShadow: "0 12px 28px rgba(0,0,0,.22)",
    gridColumn: "span 12",
  },
  row: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap" as const,
    alignItems: "center",
    marginBottom: "12px",
  },
  rowTight: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap" as const,
    alignItems: "center",
    marginBottom: "12px",
  },
  fieldGroup: {
    flex: 1,
  },
  label: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    marginBottom: "6px",
    color: "#eef2ff",
  },
  miniLabel: {
    fontSize: "12px",
    fontWeight: "600",
    color: "#9fb0d0",
  },
  pill: {
    border: "1px solid #2b3957",
    background: "#0d1526",
    color: "#9fb0d0",
    borderRadius: "999px",
    padding: "7px 12px",
    fontSize: "12px",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  input: {
    width: "100%",
    background: "#0c1324",
    color: "#eef2ff",
    border: "1px solid #2b3957",
    borderRadius: "12px",
    padding: "12px",
    fontSize: "14px",
    fontFamily: "Arial, Helvetica, sans-serif",
  },
  textarea: {
    width: "100%",
    background: "#0c1324",
    color: "#eef2ff",
    border: "1px solid #2b3957",
    borderRadius: "12px",
    padding: "12px",
    fontSize: "14px",
    minHeight: "150px",
    fontFamily: "Arial, Helvetica, sans-serif",
    marginBottom: "12px",
  },
  status: {
    border: "1px solid #2b3957",
    background: "#0c1324",
    borderRadius: "14px",
    padding: "12px",
    color: "#9fb0d0",
    fontSize: "14px",
    marginTop: "12px",
  },
  sceneList: {
    display: "grid",
    gap: "10px",
    marginTop: "12px",
  },
  sceneItem: {
    border: "1px solid #2b3957",
    background: "#0c1324",
    borderRadius: "14px",
    padding: "12px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  sceneItemActive: {
    borderColor: "#7dd3fc",
    boxShadow: "0 0 0 1px #7dd3fc inset",
  },
  small: {
    fontSize: "12px",
    color: "#9fb0d0",
    marginTop: "4px",
  },
  voiceTable: {
    display: "grid",
    gap: "10px",
  },
  voiceRow: {
    display: "grid",
    gridTemplateColumns: "1.1fr 1fr 0.6fr 0.6fr",
    gap: "10px",
    alignItems: "center",
    border: "1px solid #2b3957",
    borderRadius: "14px",
    background: "#0c1324",
    padding: "10px",
  },
  speaker: {
    color: "#7dd3fc",
    fontSize: "12px",
    fontWeight: "700",
    letterSpacing: "1px",
    marginBottom: "8px",
    textTransform: "uppercase",
  },
  dialogue: {
    fontSize: "24px",
    lineHeight: 1.3,
    minHeight: "80px",
    color: "#eef2ff",
  },
  prompt: {
    marginTop: "12px",
    color: "#fbbf24",
    fontWeight: "700",
  },
  lineBox: {
    minHeight: "220px",
    border: "1px solid #2b3957",
    borderRadius: "18px",
    background: "#0c1324",
    padding: "18px",
  },
  buttonPrimary: {
    border: "0",
    borderRadius: "12px",
    padding: "12px 16px",
    fontWeight: "700",
    cursor: "pointer",
    background: "#7dd3fc",
    color: "#082f49",
    fontSize: "14px",
    flex: 1,
  },
  buttonSecondary: {
    border: "0",
    borderRadius: "12px",
    padding: "12px 16px",
    fontWeight: "700",
    cursor: "pointer",
    background: "#334155",
    color: "#eef2ff",
    fontSize: "14px",
    flex: 1,
  },
  buttonSuccess: {
    border: "0",
    borderRadius: "12px",
    padding: "12px 16px",
    fontWeight: "700",
    cursor: "pointer",
    background: "#86efac",
    color: "#052e16",
    fontSize: "14px",
    flex: 1,
  },
  buttonWarn: {
    border: "0",
    borderRadius: "12px",
    padding: "12px 16px",
    fontWeight: "700",
    cursor: "pointer",
    background: "#fbbf24",
    color: "#422006",
    fontSize: "14px",
    flex: 1,
  },
  buttonDanger: {
    border: "0",
    borderRadius: "12px",
    padding: "12px 16px",
    fontWeight: "700",
    cursor: "pointer",
    background: "#ef4444",
    color: "#fff",
    fontSize: "14px",
    flex: 1,
  },
  sourceTab: {
    borderTop: "1px solid #2b3957",
    borderRight: "1px solid #2b3957",
    borderBottom: "1px solid #2b3957",
    borderLeft: "1px solid #2b3957",
    borderRadius: "12px 12px 0 0",
    padding: "10px 18px",
    fontWeight: "700",
    cursor: "pointer",
    background: "#0c1324",
    color: "#9fb0d0",
    fontSize: "14px",
    transition: "all 0.2s",
  },
  sourceTabActive: {
    background: "#1e293b",
    color: "#7dd3fc",
    borderTop: "1px solid #7dd3fc",
    borderRight: "1px solid #7dd3fc",
    borderLeft: "1px solid #7dd3fc",
    borderBottom: "2px solid #7dd3fc",
  },
  checkboxGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
    marginTop: "12px",
  },
};

export default styles;
